matrix:
  include:
  - stage: Tox
    language: 'python'
    python:
    - "3.7"
    install: pip install tox-travis
    script: tox
  - stage: Vue
    language: 'node_js'
    node_js:
    - 10
    python:
    - "3.7"
    install:
    - pip install -r require.txt --user
    - apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
    - cd myclient
    - npm ci
    script:
    - python ../app.py &
    - npm run serve &
    - npm test